display_name: Homiefroxy

packager: chen08209
packagerEmail: chen08209@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - Homiefroxy
  - Clash
  - ClashMeta
  - Proxy

generic_name: Homiefroxy

group: Applications/Internet

startup_notify: true
