display_name: Homiefroxy

icon: ./assets/images/icon.png

keywords:
  - Homiefroxy
  - Clash
  - ClashMeta
  - Proxy

generic_name: Homiefroxy

categories:
  - Network

startup_notify: true

include: []
