display_name: Homiefroxy
package_name: Homiefroxy
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - Homiefroxy
  - Clash
  - ClashMeta
  - Proxy

generic_name: Homiefroxy

categories:
  - Network

startup_notify: true
